vip_address: 192.168.0.140
vip_interface: eth0
vrrp_id: 51

haproxy_frontend_port: 80
haproxy_backend_servers:
  - { name: web1, ip: 192.168.0.1, port: 80 }
  - { name: web2, ip: 192.168.0.103, port: 80 }

